### ISSUE TITLE
Unable to Connect to VPN

### ISSUE THREAD

**Issue by allieraej** [net-angel/netangel-protection-android#58] opened 2017-04-06 15:54 UTC
We've had multiple customers who have been unable to get their devices connected to NetAngel through the Android App. They report that they log in, name their device, and when they click "prevent uninstall" it skips over to the "connect to NetAngel" page. One customer in particular noted that she was able to successfully download it onto her Samsung Galaxy phone, and when she clicked "Prevent Uninstall" the box with the explanation popped up, and then she clicked the arrow to go to the next screen. On her son's phone, a Google Pixel, however, after clicking "prevent uninstall" it simply skipped over and began to try to connect to netangel without success. 

@klinker24 @eterry1388

**Comment by klinker24** [comment] 2017-04-06 16:34
Different devices will handle that device admin differently, I don't think that is a huge concern, as long as it gets set up as an admin.

I started working on the connection issues, but I really just need more logging information for them, at this point. I made a comment [here](https://github.com/net-angel/netangel-protection-android/issues/29). And I have added expanded logging through Firebase, if we can get #54 merged. This should at least be a start to the connection issues. I have a feeling they have something to do with the `ics-openvpn` dependency, but can't say for sure yet.

What is the percent of people that aren't able to connect to the VPN?

**Comment by allieraej** [comment] 2017-04-10 23:39
So far, I've had about 4 people unable to install NetAngel successfully on their device. One Google Pixel phone, two HTC One phones, and a Samsung tablet. @klinker24

**Comment by eterry1388** [comment] 2017-04-12 21:09
@klinker24 I think we found the issue.  Seems to be the new "Wi-Fi Assistant" feature on Android 7.0.  It creates a VPN profile that has "Always-On-VPN".  When Wi-Fi Assistant is disabled on the phone and that VPN profile is deleted, it connects just fine.

Any thoughts on what we can do here on our side?  Any way to delete all existing VPN profiles before connecting to ours?  Or any way to disable all the "Always-On-VPN" VPN profiles before connecting to ours?

**Comment by klinker24** [comment] 2017-04-12 21:31
I will have to do some research on this, unfortunately I don't know the answer to those questions. 

I don't want to be too quick to say this, but we probably cannot delete or touch the existing VPN profiles from our app, no. If that is the case, but I am able to detect them, I would definitely be able to make something to walk the user through disconnecting that profile manually (or turning off the "always-on" functionality).

**Comment by klinker24** [comment] 2017-04-14 01:45
So I have some news on this one, after digging around. Not great news, unfortunately.

I am able to reproduce it. I have a Pixel, which has the WiFi Assistant VPN. When I turn on the "Always on VPN", it will immediately quit out of the connection, if I try to connect to the NetAngel VPN. 

The way that the VPN works is that we first request access to use the VPN, which you can see in [this screenshot](https://camo.githubusercontent.com/aa9149fdcb22e89f55ea0a1cef9a8147a500c565/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f41617178473559464f6a3177546f73782d616b61485f52794f556761344c335f574c365678754b66525954565162354541686c50303630524a4650685a6178314e34383d683930302d7277). When that dialog is up, we have to listen for the "Result" [here](https://github.com/net-angel/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/ui/ConnectVpnActivity.java#L75). 

If the user allows it, we will get a [RESULT_OK](https://github.com/net-angel/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/ui/ConnectVpnActivity.java#L78). If they cancel or back out of that request, we get a [RESULT_CANCELLED](https://github.com/net-angel/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/ui/ConnectVpnActivity.java#L80) callback. The problem is that when this "Always on VPN" is active, the system will immediately give back the `RESULT_CANCELLED` callback, without showing that request dialog to the user. Even if they have accepted the request in the past, it still will immediately fail at this point.

After that, I thought that this "Always on VPN" may show up in the `NetworkInterfaces`. I use the `NetworkInterfaces` that Android gives us in the system, to tell if we are [currently connected to a VPN or not](https://github.com/net-angel/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/ui/ConnectVpnActivity.java#L80). I thought that it would show up here, even if it isn't defined as `tun` or `pptp` like I am currently checking for. Unfortunately, it does not show up in that list either.

---

So, it seems like we do not have a way to know if this "Always on VPN" is active or not, since cancelling that VPN request gives us the same result callback as the WiFi Assistant. 

The only solution that I am seeing is a manual one for the user. 

If they get this `RESULT_CANCELLED` callback, then we should pop up a dialog, asking if they really cancelled this request. If they say that they did not, then we tell them that there is a conflict with connecting to the NetAngel service, and that they need to disable the "Always On VPN" for their device. I can show them a screenshot of that, right in the dialog, and I can take them directly to the VPN list, so that they can disable it. Then they would have to come back to NetAngel and turn on the VPN again. 

It isn't too many steps, but still is a bother for the user. Unfortunately, I am not coming up with any other solutions at this time. I will think about it more, over the weekend.

**Comment by klinker24** [comment] 2017-04-19 14:08
@eterry1388 if it is ok with you, I am going to go ahead and implement the solution that I outlined here. Not ideal, by any means, but I haven't come up with any better ideas for it, unfortunately.

**Closed** 2017-04-27 02:36 UTC
Labels: bug
